# Generated by Django 5.0.4 on 2024-04-25 04:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0002_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('Description', models.CharField(max_length=200)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters_managed', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
