# Generated by Django 5.0.4 on 2024-04-25 06:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0004_theater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movies_managed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
