# Generated by Django 5.0.4 on 2024-04-25 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0006_theater'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Theater',
        ),
    ]
