# Generated by Django 5.0.4 on 2024-04-25 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0007_delete_theater'),
    ]

    operations = [
        migrations.CreateModel(
            name='Theater',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('theater_name', models.CharField(max_length=255)),
                ('place', models.TextField(max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='media/')),
                ('manager_theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters_managed', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='theaters', to='theater_app.movie')),
            ],
        ),
    ]
