# Generated by Django 5.0.4 on 2024-04-27 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0009_rename_place_theater_location'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='manager',
            new_name='admin',
        ),
    ]
