# Generated by Django 5.0.4 on 2024-04-27 07:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0010_rename_manager_movie_admin'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='admin',
            new_name='manager',
        ),
    ]
