# Generated by Django 4.2.11 on 2024-04-27 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0011_rename_admin_movie_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='manager',
            new_name='admin',
        ),
    ]
