# Generated by Django 5.0.4 on 2024-04-29 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0012_rename_manager_movie_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time_slot_1', models.BooleanField(default=False)),
                ('time_slot_2', models.BooleanField(default=False)),
                ('time_slot_3', models.BooleanField(default=False)),
                ('time_slot_4', models.BooleanField(default=False)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='theater_app.theater')),
            ],
        ),
    ]
