# Generated by Django 5.0.4 on 2024-04-30 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0022_alter_theater_time_slot_1_alter_theater_time_slot_2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='theater',
            name='time_slot_1',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='time_slot_2',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='time_slot_3',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='theater',
            name='time_slot_4',
            field=models.TextField(blank=True, max_length=25, null=True),
        ),
    ]
