# Generated by Django 5.0.4 on 2024-05-01 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0024_alter_theater_time_slot_1_alter_theater_time_slot_2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=10)),
                ('booked', models.BooleanField(default=False)),
                ('time_slot', models.CharField(max_length=20)),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='theater_app.theater')),
            ],
        ),
    ]
