# Generated by Django 5.0.4 on 2024-05-03 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0031_seat_booking'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Booking',
        ),
    ]
