# Generated by Django 5.0.4 on 2024-05-03 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0034_booking_movie_booking_theater_booking_time_slot_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booked_seat_numbers',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
