# Generated by Django 5.0.6 on 2024-05-14 09:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theater_app', '0037_userchat_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchat',
            name='created_at',
        ),
    ]
